In [1]:
!pip freeze | grep scikit-learn

scikit-learn==1.5.0

In [2]:
!python -V

Python 3.10.12

In [3]:
import pickle
import pandas as pd

In [4]:
with open('model.bin', 'rb') as f_in:
    dv, model = pickle.load(f_in)

In [5]:
categorical = ['PULocationID', 'DOLocationID']

def read_data(filename):
    df = pd.read_parquet(filename)
    
    df['duration'] = df.tpep_dropoff_datetime - df.tpep_pickup_datetime
    df['duration'] = df.duration.dt.total_seconds() / 60

    df = df[(df.duration >= 1) & (df.duration <= 60)].copy()

    df[categorical] = df[categorical].fillna(-1).astype('int').astype('str')
    
    return df

In [6]:
year = 2023
month = 3
input_file = f'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year:04d}-{month:02d}.parquet'

df = read_data(input_file)

In [7]:
dicts = df[categorical].to_dict(orient='records')
X_val = dv.transform(dicts)
y_pred = model.predict(X_val)

In [8]:
y_pred

array([16.24590642, 26.1347962 , 11.88426424, ..., 11.59533603,
       13.11317847, 12.89999218], shape=(3316216,))

In [9]:
std_dev = pd.Series(y_pred).std()
print(f"Standard deviation of predicted duration: {std_dev:.3f}")

Standard deviation of predicted duration: 6.247

In [10]:
df['ride_id'] = f'{year:04d}/{month:02d}_' + df.index.astype('str')

In [11]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,duration,ride_id
0,2,2023-03-01 00:06:43,2023-03-01 00:16:43,1.0,0.00,1.0,N,238,42,2,...,1.0,0.5,0.00,0.0,1.0,11.10,0.0,0.00,10.000000,2023/03_0
1,2,2023-03-01 00:08:25,2023-03-01 00:39:30,2.0,12.40,1.0,N,138,231,1,...,6.0,0.5,12.54,0.0,1.0,76.49,2.5,1.25,31.083333,2023/03_1
2,1,2023-03-01 00:15:04,2023-03-01 00:29:26,0.0,3.30,1.0,N,140,186,1,...,3.5,0.5,4.65,0.0,1.0,28.05,2.5,0.00,14.366667,2023/03_2
3,1,2023-03-01 00:49:37,2023-03-01 01:01:05,1.0,2.90,1.0,N,140,43,1,...,3.5,0.5,4.10,0.0,1.0,24.70,2.5,0.00,11.466667,2023/03_3
4,2,2023-03-01 00:08:04,2023-03-01 00:11:06,1.0,1.23,1.0,N,79,137,1,...,1.0,0.5,2.44,0.0,1.0,14.64,2.5,0.00,3.033333,2023/03_4

In [12]:
df_result = pd.DataFrame()
df_result['ride_id'] = df['ride_id']
#df_result['tpep_pickup_datetime'] = df['tpep_pickup_datetime']
#df_result['PULocationID'] = df['PULocationID']
#df_result['DOLocationID'] = df['DOLocationID']
#df_result['actual_duration'] = df['duration']
df_result['predicted_duration'] = y_pred
#df_result['diff'] = df_result['actual_duration'] - df_result['predicted_duration']

In [13]:
df_result

                 ride_id  predicted_duration
0              2023/03_0           16.245906
1              2023/03_1           26.134796
2              2023/03_2           11.884264
3              2023/03_3           11.997720
4              2023/03_4           10.234486
...                  ...                 ...
3403761  2023/03_3403761           11.952635
3403762  2023/03_3403762           20.049958
3403763  2023/03_3403763           11.595336
3403764  2023/03_3403764           13.113178
3403765  2023/03_3403765           12.899992

[3316216 rows x 2 columns]

In [14]:
!mkdir output

In [15]:
output_file = f'output/yellow_tripdata_{year:04d}-{month:02d}.parquet'

df_result.to_parquet(
    output_file,
    engine='pyarrow',
    compression=None,
    index=False
)

In [16]:
!ls -lh output/

total 66M
-rw-rw-r-- 1 jdanussi jdanussi 66M jun 23 17:42 yellow_tripdata_2023-03.parquet

In [17]:
mean_pred = y_pred.mean()
print(f"Mean predicted duration: {mean_pred:.2f}")

Mean predicted duration: 14.20